### ISSUE TITLE
Error when using : nimble install voicepeaky

### ISSUE THREAD

**Issue by levinh822002** [solaoi/voicepeaky#1]
Installing voicepeaky@1.0.5
   Building voicepeaky/voicepeaky.exe using c backend
C:\Users\PC\.nimble\pkgs2\httpbeast-0.4.1-b23e57a401057dcb9b7fae1fb8279a6a2ce1d0b8\httpbeast.nim(45, 14) Error: ambiguous identifier: 'SocketHandle' -- use one of the following:
  winlean.SocketHandle: SocketHandle
  posix.SocketHandle: SocketHandle
       Tip: 16 messages have been suppressed, use --verbose to show them.
nimble.nim(229)          buildFromDir

    Error:  Build failed for the package: voicepeaky

**Comment by solaoi** [comment]
Thank you for bringing this to our attention.
However, this command is only supported on MacOS.
I've added a MacOS label to the README for clarity.
